# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.13                     # https://pyreadiness.org/3.9/
  - pip=22.1.2   
  - pip:
    - rpaframework==23.0.0            # https://rpaframework.org/releasenotes.html
    - dop-rpaframework==1.2.4 
    - robocorp
    - robocorp-browser==2.3.3
    - deep-translator
    - validators